version: "3.7"

services:
    gui:
        image: yourimagename/gui
        build:
            context: gui/
        ports:
        - 8080:8080
    lex:
        image: yourimagename/lex
        build:
            context: lex
        ports:
        - 8085:8085

